### ISSUE TITLE
formatToParts capability is not included in the last publish

### ISSUE THREAD

**Issue by deecewan** [yahoo/date-time-format-timezone#22]
As can be seen on [unpkg](https://unpkg.com/date-time-format-timezone@1.0.21-alpha.2/build/src/code/polyfill.js), the `latest` release doesn't include `formatToParts`.

This functionality existed before the release was cut, so I'm not sure what's gone wrong (perhaps no build before publishing?).

**Comment by benmccann** [comment]
@markandey and ideas on this one?

**Comment by markandey** [comment]
I will ship this soon

**Comment by markandey** [comment]
Fixing some tests broken on latest firefox

**Comment by markandey** [comment]
Fixed it !!
